const sectionHeadingStyle = {
  color: '#1E3A5F',
};

function PrivacyPage() {
  return (
    <main className="bg-light">
      <div className="container py-5">
        <div className="mx-auto" style={{ maxWidth: '900px' }}>
          <div
            className="rounded-4 shadow-sm border p-4 p-md-5 bg-white"
            style={{ borderColor: 'rgba(30, 58, 95, 0.12)' }}
          >
            <p
              className="text-uppercase fw-semibold mb-2"
              style={{ color: '#0D9488', letterSpacing: '0.08em', fontSize: '0.85rem' }}
            >
              HealingWings Sanctuary
            </p>
            <h1 className="display-6 fw-bold mb-3" style={{ color: '#1E3A5F' }}>
              Privacy Policy
            </h1>
            <p className="text-muted mb-4">Last updated: April 6, 2026</p>
            <p className="lead">
              HealingWings Sanctuary uses this website and application to support
              donor engagement, staff operations, and secure case management.
              Because this system may contain highly sensitive information about
              survivors, staff, donors, and partners, we design it to collect the
              minimum data needed and to protect that data with role-based access
              controls and security safeguards.
            </p>

            <hr className="my-4" />

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Who we are
            </h2>
            <p>
              HealingWings Sanctuary is a nonprofit organization supporting girls
              who are survivors of trafficking and abuse. This privacy policy
              explains how we collect, use, store, and disclose personal data
              when you visit our website, create an account, sign in, donate,
              communicate with us, or use the secure parts of the application.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              What data we collect
            </h2>
            <p>Depending on how you interact with the site, we may collect:</p>
            <ul className="mb-3">
              <li>
                Identity and account information, such as name, email address,
                username, role, and encrypted authentication credentials.
              </li>
              <li>
                Security information, such as sign-in history, device/browser
                information, recovery codes, and multi-factor authentication
                settings.
              </li>
              <li>
                Donor and supporter information, such as donation history,
                supporter type, contribution records, and communication history.
              </li>
              <li>
                Staff-entered operational information needed to run the
                organization, including safehouse, resident, case, intervention,
                visitation, incident, and reporting records.
              </li>
              <li>
                Technical information, such as IP address, browser type, basic
                request logs, and security event data generated by our hosting
                and application infrastructure.
              </li>
              <li>
                Cookie and local storage preference data required to keep users
                signed in securely and remember cookie acknowledgment choices.
              </li>
            </ul>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              How we collect your data
            </h2>
            <ul className="mb-3">
              <li>You provide data directly when you register, sign in, donate, or contact us.</li>
              <li>
                Authorized staff users create and update operational records
                inside the secure application.
              </li>
              <li>
                Some data are collected automatically through server logs,
                authentication flows, and essential browser storage used for
                security and session continuity.
              </li>
              <li>
                If you use Google sign-in, Google provides authentication data
                needed to complete the external login flow.
              </li>
            </ul>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              How we use your data
            </h2>
            <p>We use personal data to:</p>
            <ul className="mb-3">
              <li>Create and manage user accounts.</li>
              <li>Authenticate users and secure access to restricted data.</li>
              <li>Operate donor, case management, and reporting workflows.</li>
              <li>Maintain auditability, system integrity, and platform security.</li>
              <li>Respond to inquiries and support requests.</li>
              <li>Meet legal, safeguarding, and operational obligations.</li>
              <li>
                Generate anonymized or aggregated public-facing impact information
                that does not expose personal identities.
              </li>
            </ul>
            <p>
              We do not sell personal data. We do not use advertising cookies,
              behavioral advertising, or third-party marketing trackers on this
              site.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Legal bases for processing
            </h2>
            <p>
              Where GDPR applies, we process personal data under one or more of
              the following legal bases:
            </p>
            <ul className="mb-3">
              <li>Consent, where you choose to provide information or use optional sign-in methods.</li>
              <li>Contract, when processing is necessary to provide account access or donor services.</li>
              <li>
                Legitimate interests, including securing the platform, improving
                operations, and administering the organization responsibly.
              </li>
              <li>
                Legal obligation or vital interests, where safeguarding,
                incident handling, or compliance duties require processing.
              </li>
            </ul>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Cookies and similar technologies
            </h2>
            <p>
              We use browser cookies and local storage under two tiers you select in the
              on-screen banner:
            </p>
            <ul className="mb-3">
              <li>
                <strong>Necessary only</strong> — authentication cookies, security-related
                storage, and a small record of your consent choice. This includes data needed
                to stay signed in and to complete Google or other external login. If you use
                password sign-in, the app may mirror session information in local storage so
                the experience works reliably across browsers (including some mobile
                browsers that restrict cookies).
              </li>
              <li>
                <strong>Accept all</strong> — everything in “Necessary only,” plus optional
                preferences we may save under keys beginning with{' '}
                <code className="small">intex-optional-</code> (for example dismissing tips).
                Choosing “Necessary only” removes any existing optional preference keys from
                this browser.
              </li>
            </ul>
            <p className="mb-3">
              We do not use advertising or analytics cookies. External providers (such as
              Google) may set their own cookies when you use their sign-in button; their
              policies apply to those technologies.
            </p>
            <p>
              You can block cookies through your browser settings, but some parts of the
              site, including login and security features, may no longer function correctly.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Sharing and disclosure
            </h2>
            <p>We share personal data only when needed to operate the service responsibly, including with:</p>
            <ul className="mb-3">
              <li>Hosting, identity, and infrastructure providers that support the application.</li>
              <li>Authentication providers, such as Google, when you choose external sign-in.</li>
              <li>
                Authorized staff, administrators, and service providers who need
                access to perform their responsibilities.
              </li>
              <li>Regulators, law enforcement, or safeguarding authorities when legally required.</li>
            </ul>
            <p>
              We do not disclose resident or donor information publicly except in
              anonymized, aggregated, or de-identified form.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              International transfers
            </h2>
            <p>
              Our technology providers may process data in countries outside your
              own. When that occurs, we rely on appropriate contractual,
              technical, and organizational safeguards intended to protect
              personal data during cross-border transfers.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Data retention
            </h2>
            <p>
              We retain personal data only for as long as necessary for the
              purposes described in this policy, including account management,
              donor stewardship, safeguarding, reporting, security, and legal
              compliance. Retention periods vary by record type. For example:
            </p>
            <ul className="mb-3">
              <li>Account and authentication records are retained while an account is active and for a limited period afterward for security and audit purposes.</li>
              <li>Donation and financial records are retained as required for accounting, reporting, and compliance.</li>
              <li>
                Sensitive case records may be retained longer where required for
                safeguarding, continuity of care, or legal obligations.
              </li>
              <li>
                When data are no longer required, we delete them, anonymize them,
                or restrict access according to the record type and system needs.
              </li>
            </ul>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Data protection rights
            </h2>
            <p>
              Depending on your location and applicable law, you may have the
              right to:
            </p>
            <ul className="mb-3">
              <li>Access the personal data we hold about you.</li>
              <li>Request correction of inaccurate or incomplete data.</li>
              <li>Request deletion of your data in certain circumstances.</li>
              <li>Request restriction of processing.</li>
              <li>Object to certain processing activities.</li>
              <li>Request transfer of your data to you or another provider, where applicable.</li>
              <li>Withdraw consent where processing is based on consent.</li>
              <li>Lodge a complaint with a data protection authority.</li>
            </ul>
            <p>
              We may need to verify your identity before acting on a request. We
              will respond within the time required by applicable law.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Children and sensitive data
            </h2>
            <p>
              This organization serves minors and survivors of abuse. We treat
              related operational records as highly sensitive and restrict access
              to authorized personnel with a legitimate need to know. Public
              portions of the site are not intended for children to submit case
              information directly.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Security
            </h2>
            <p>
              We use administrative, technical, and organizational safeguards
              designed to protect personal data, including encrypted transport
              over HTTPS, authentication controls, role-based authorization,
              content security protections, and restricted access to sensitive
              records. No system can guarantee absolute security, but we work to
              reduce risk and limit access appropriately.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Third-party sites
            </h2>
            <p>
              Our site may link to third-party websites or services. Their
              privacy practices are governed by their own policies, not this one.
              We encourage you to review those policies before providing personal
              data to third parties.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Changes to this policy
            </h2>
            <p>
              We may update this privacy policy from time to time to reflect
              changes to the application, legal requirements, or operational
              practices. When we do, we will post the updated version on this
              page and revise the “Last updated” date above.
            </p>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Contact us
            </h2>
            <p>
              If you have questions about this privacy policy or want to exercise
              your privacy rights, contact us at:
            </p>
            <div className="rounded-3 p-3 p-md-4" style={{ background: '#F8FAFC' }}>
              <p className="mb-2 fw-semibold">HealingWings Sanctuary</p>
              <p className="mb-1">Email: info@healingwings.org</p>
              <p className="mb-1">Phone: +63 2 XXXX XXXX</p>
              <p className="mb-0">Address: 123 Sampaguita Street, Manila, Philippines 1000</p>
            </div>

            <h2 className="h4 fw-bold mt-4 mb-3" style={sectionHeadingStyle}>
              Complaints
            </h2>
            <p className="mb-0">
              If you believe we have not handled your personal data properly, you
              may contact us first so we can try to resolve the issue. You may
              also lodge a complaint with the data protection or privacy
              regulator that applies in your jurisdiction.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}

export default PrivacyPage;
